# ============================================
# Variables
# ============================================

variable "lambda_package_version" {
  description = "Git commit hash for Lambda package versioning"
  type        = string
}

variable "s3_bucket" {
  description = "S3 bucket for Lambda packages"
  type        = string
  default     = "keobiz-lambda-packages"
}

variable "s3_prefix" {
  description = "S3 prefix for Lambda packages"
  type        = string
  default     = "dynamic-project"
}

# ============================================
# Dynamic Function Configuration
# ============================================
# This is populated from functions.auto.tfvars.json
# generated by: python scripts/generate-tf-config.py

variable "functions" {
  description = "Map of function configurations (auto-generated from config.json files)"
  type = map(object({
    name                  = string
    description           = string
    handler               = string
    runtime               = string
    memory_size           = map(number)
    timeout               = map(number)
    reserved_concurrency  = optional(any, -1)
    enable_api_gateway    = bool
    api_routes            = list(object({ method = string, path = string }))
    enable_scheduling     = bool
    schedules             = list(any)
    enable_sqs            = bool
    sqs_batch_size        = optional(number, 10)
    sqs_batch_window      = optional(number, 30)
    env_vars              = map(string)
    tags                  = map(string)
  }))
  default = {}
}

